export const GET_BREEDS = "GET_BREEDS";
export const GET_CATS = "GET_CATS";
export const SET_SELECTED_BREED = "SET_SELECTED_BREED";
export const SET_LOADING = "SET_LOADING";
export const SET_SEARCH_OPTIONS = "SET_SEARCH_OPTIONS";
